### ISSUE TITLE
Issues with reproducing the .realign.sorted.bed file

### ISSUE THREAD

**Issue by GuillaumeHolley** [mebbert/Dark_and_Camouflaged_genes#1]
Hello,

First of all, thank you for this interesting work and making available your code to the community.

I am trying to reproduce some of the steps of your pipeline using our own data and I noticed something strange in the .realign.sorted.bed I am producing compared to the one your are making available here.
Particularly, your .realign.sorted.bed contains the following coordinates for CR1 (among other coordinates):
```
chr1	207533408	207533588	CR1_10;CR1_26;CR1_18	3
chr1	207551963	207552143	CR1_18;CR1_10;CR1_26	3
chr1	207569058	207569238	CR1_26;CR1_18;CR1_10	3
```

But using the reference genome genome hg38 and the Ensemble build 93, I obtain:
```
chr1	207533408	207533588	CR1_10;CR1_26;CR1_18	3
chr1	207551963	207552143	CR1_18;CR1_10;CR1_26	3
chr1	207569058	207569122	CR1_26;CR1_18;CR1_10	3
chr1	207569122	207569238	CR1_UTR_2;CR1_18;CR1_10	3
```

Basically, your last CR1_26 coordinates show a 180bp region but in my case, it is CR1_26 + CR1_UTR_2 (the 2 last coordinates) which is 180bp long. While CR1_10, CR1_18 and CR1_26 are reported 3 times, CR1_UTR_2 is only reported one time. I checked in the GFF3 file of Ensemble build 93 and indeed, CR1_26 has coordinates chr1:207,569,058-207,569,122 and should be 64bp long.

Using Ensemble build 98, I obtain something even more strange:
```
chr1	207533408	207533588	CR1_10;AL137789.1_intron_2;AL137789.1_1;CR1_UTR_2;CR1_18	5
chr1	207551963	207552143	CR1_18;CR1_10;AL137789.1_intron_2;AL137789.1_1;CR1_UTR_2  5
chr1	207569058	207569122	CR1_26;AL137789.1_intron_;CR1_182;AL137789.1_1;CR1_10	5
chr1	207569122	207569238	CR1_UTR_2;CR1_18;CR1_10;AL137789.1_intron_2;AL137789.1_1	5
``` 
CR1_26 is this time reported similar to CR1_10 and CR1_18 only once while CR1_UTR_2 is reported 3 times.

Maybe I am missing a step somewhere in your pipeline where CR1_26 is merged with CR1_UTR_2 but at that point, I do not understand nor see how to obtain the coordinates that you have for chr1:207,569,058-207,569,122 (CR1_26) while I get 2 coordinates corresponding to CR1_26 and CR1_UTR_2.

I would appreciate any help and insights on this problem.

Thank you.

**Comment by tjense25** [comment]
Hey,

Thanks for your interest in our research!

Looks like some of our code was out of date. If you pull again and rerun step 04_PREPARE_ANNOTATION_BED, I think this issue should be resolved.

The inconsistency you're seeing stems from a difference in our gene-level annotation files. Looks like yours has CR1 exon 26 adjacent to a 3' UTR. This UTR shouldn't actually be there and is a result of erroneously including a nonsense-mediated-decay transcript when collapsing transcript-level annotations down to the gene level. The up-to-date code will filter out this NMD transcript and you should see the correct 180bp CR1 exon 26 camouflaged to exon 10 and 18. Sorry we didn't catch this earlier! 

Let us know if this is still an issue or if you run into any other problems implementing our pipeline. We're happy to help ☺️.

Tanner

**Comment by GuillaumeHolley** [comment]
Sorry I couldn't get back to you before today, thank you for the quick answer! The script works very well now on build 93 and I can indeed see exon 26 camouflaged by exon 10 and 18 :)

However, when it comes to the Ensemble build 98, I obtain a lot more camouflaged introns mixed with exons for CR1. If I take the example of coordinates chr1:207,569,058-207,569,238 (CR1_26), I now see:
```
chr1	207569058	207569238	CR1_26;CR1_intron_9;CR1_10;AL137789.1_intron_2;CR1_intron_18;CR1_18;CR1_intron_10;AL137789.1_1;CR1_intron_17;CR1_intron_25;CR1_intron_26      11
```

Thank you for the help!

Guillaume

**Comment by mpage21** [comment]
Closing this as it is an old issue

**Comment by GuillaumeHolley** [comment]
Hi @mpage21,

I remember that I also reproduced the issue I last described with Ensemble build 98 on a more recent (>98) build of Ensemble. Do you know if there is an explanation for the increase of camouflaged introns mixed with exons for CR1 between build 93 and 98 or is that a code issue that was fixed?

Thank you,
Guillaume

**Comment by mpage21** [comment]
Hi Guillaume,

We don't think the issue resides in the code, but it likely due to changes in annotations between the builds. Unfortunately we don't have the funding to support this pipeline to the extent we would like. 

Thank you,
Maddy
