### ISSUE TITLE
Alt-aware alignment files?

### ISSUE THREAD

**Issue by KaitlynSparks** [mebbert/Dark_and_Camouflaged_genes#3]
Hi there,

Thank you for your research, and for making this repository public.

Our group is running the pipeline using our own data. We were wondering whether to use our alt-aware alignment files or our non-alt-aware files. 

Would this make a difference?

Thanks,
Kaitlyn

**Comment by mpage21** [comment]
Hi Kaitlyn,

We would suggest using the non-alt-aware files. The alt-aware files would most likely add another layer of complication with the camo regions.  

Best,
Maddy
